version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Berlin
    reviewers:
      - jackmu95
    labels:
      - "Type: CI"
      - "Type: Dependencies"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: Europe/Berlin
    ignore:
      - dependency-name: "bootstrap"
        versions: [">=5.0.0"]
      - dependency-name: "clean-css-cli"
        versions: [">=5.0.0"]
      - dependency-name: "html-loader"
        versions: [">=2.0.0"]
      - dependency-name: "prettier"
        versions: [">1.14.3"]
      - dependency-name: "sass-loader"
        versions: [">=11.0.0"]
      - dependency-name: "@vue/test-utils"
        versions: [">=2.0.0"]
    reviewers:
      - jackmu95
    labels:
      - "Type: Dependencies"
    versioning-strategy: increase
    rebase-strategy: disabled
