tasks:
  - init: yarn install
  - command: yarn run watch
  - command: yarn run docs-dev
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
