// --- BEGIN AUTO-GENERATED FILE ---
//
// @IconsVersion: 1.2.1
// @Generated: 2020-12-14T13:38:30.765Z
//
// This file is generated on each build. Do not edit this file!

import Vue from 'vue'
import { BvComponent } from '../'

// --- BootstrapVue custom icons ---

export declare class BIconBlank extends BvComponent {}

// --- Bootstrap Icons ---

export declare class BIconAlarm extends BvComponent {}

export declare class BIconAlarmFill extends BvComponent {}

export declare class BIconAlignBottom extends BvComponent {}

export declare class BIconAlignCenter extends BvComponent {}

export declare class BIconAlignEnd extends BvComponent {}

export declare class BIconAlignMiddle extends BvComponent {}

export declare class BIconAlignStart extends BvComponent {}

export declare class BIconAlignTop extends BvComponent {}

export declare class BIconAlt extends BvComponent {}

export declare class BIconApp extends BvComponent {}

export declare class BIconAppIndicator extends BvComponent {}

export declare class BIconArchive extends BvComponent {}

export declare class BIconArchiveFill extends BvComponent {}

export declare class BIconArrow90degDown extends BvComponent {}

export declare class BIconArrow90degLeft extends BvComponent {}

export declare class BIconArrow90degRight extends BvComponent {}

export declare class BIconArrow90degUp extends BvComponent {}

export declare class BIconArrowBarDown extends BvComponent {}

export declare class BIconArrowBarLeft extends BvComponent {}

export declare class BIconArrowBarRight extends BvComponent {}

export declare class BIconArrowBarUp extends BvComponent {}

export declare class BIconArrowClockwise extends BvComponent {}

export declare class BIconArrowCounterclockwise extends BvComponent {}

export declare class BIconArrowDown extends BvComponent {}

export declare class BIconArrowDownCircle extends BvComponent {}

export declare class BIconArrowDownCircleFill extends BvComponent {}

export declare class BIconArrowDownLeft extends BvComponent {}

export declare class BIconArrowDownLeftCircle extends BvComponent {}

export declare class BIconArrowDownLeftCircleFill extends BvComponent {}

export declare class BIconArrowDownLeftSquare extends BvComponent {}

export declare class BIconArrowDownLeftSquareFill extends BvComponent {}

export declare class BIconArrowDownRight extends BvComponent {}

export declare class BIconArrowDownRightCircle extends BvComponent {}

export declare class BIconArrowDownRightCircleFill extends BvComponent {}

export declare class BIconArrowDownRightSquare extends BvComponent {}

export declare class BIconArrowDownRightSquareFill extends BvComponent {}

export declare class BIconArrowDownShort extends BvComponent {}

export declare class BIconArrowDownSquare extends BvComponent {}

export declare class BIconArrowDownSquareFill extends BvComponent {}

export declare class BIconArrowDownUp extends BvComponent {}

export declare class BIconArrowLeft extends BvComponent {}

export declare class BIconArrowLeftCircle extends BvComponent {}

export declare class BIconArrowLeftCircleFill extends BvComponent {}

export declare class BIconArrowLeftRight extends BvComponent {}

export declare class BIconArrowLeftShort extends BvComponent {}

export declare class BIconArrowLeftSquare extends BvComponent {}

export declare class BIconArrowLeftSquareFill extends BvComponent {}

export declare class BIconArrowRepeat extends BvComponent {}

export declare class BIconArrowReturnLeft extends BvComponent {}

export declare class BIconArrowReturnRight extends BvComponent {}

export declare class BIconArrowRight extends BvComponent {}

export declare class BIconArrowRightCircle extends BvComponent {}

export declare class BIconArrowRightCircleFill extends BvComponent {}

export declare class BIconArrowRightShort extends BvComponent {}

export declare class BIconArrowRightSquare extends BvComponent {}

export declare class BIconArrowRightSquareFill extends BvComponent {}

export declare class BIconArrowUp extends BvComponent {}

export declare class BIconArrowUpCircle extends BvComponent {}

export declare class BIconArrowUpCircleFill extends BvComponent {}

export declare class BIconArrowUpLeft extends BvComponent {}

export declare class BIconArrowUpLeftCircle extends BvComponent {}

export declare class BIconArrowUpLeftCircleFill extends BvComponent {}

export declare class BIconArrowUpLeftSquare extends BvComponent {}

export declare class BIconArrowUpLeftSquareFill extends BvComponent {}

export declare class BIconArrowUpRight extends BvComponent {}

export declare class BIconArrowUpRightCircle extends BvComponent {}

export declare class BIconArrowUpRightCircleFill extends BvComponent {}

export declare class BIconArrowUpRightSquare extends BvComponent {}

export declare class BIconArrowUpRightSquareFill extends BvComponent {}

export declare class BIconArrowUpShort extends BvComponent {}

export declare class BIconArrowUpSquare extends BvComponent {}

export declare class BIconArrowUpSquareFill extends BvComponent {}

export declare class BIconArrowsAngleContract extends BvComponent {}

export declare class BIconArrowsAngleExpand extends BvComponent {}

export declare class BIconArrowsCollapse extends BvComponent {}

export declare class BIconArrowsExpand extends BvComponent {}

export declare class BIconArrowsFullscreen extends BvComponent {}

export declare class BIconArrowsMove extends BvComponent {}

export declare class BIconAspectRatio extends BvComponent {}

export declare class BIconAspectRatioFill extends BvComponent {}

export declare class BIconAsterisk extends BvComponent {}

export declare class BIconAt extends BvComponent {}

export declare class BIconAward extends BvComponent {}

export declare class BIconAwardFill extends BvComponent {}

export declare class BIconBack extends BvComponent {}

export declare class BIconBackspace extends BvComponent {}

export declare class BIconBackspaceFill extends BvComponent {}

export declare class BIconBackspaceReverse extends BvComponent {}

export declare class BIconBackspaceReverseFill extends BvComponent {}

export declare class BIconBadge4k extends BvComponent {}

export declare class BIconBadge4kFill extends BvComponent {}

export declare class BIconBadge8k extends BvComponent {}

export declare class BIconBadge8kFill extends BvComponent {}

export declare class BIconBadgeAd extends BvComponent {}

export declare class BIconBadgeAdFill extends BvComponent {}

export declare class BIconBadgeCc extends BvComponent {}

export declare class BIconBadgeCcFill extends BvComponent {}

export declare class BIconBadgeHd extends BvComponent {}

export declare class BIconBadgeHdFill extends BvComponent {}

export declare class BIconBadgeTm extends BvComponent {}

export declare class BIconBadgeTmFill extends BvComponent {}

export declare class BIconBadgeVo extends BvComponent {}

export declare class BIconBadgeVoFill extends BvComponent {}

export declare class BIconBag extends BvComponent {}

export declare class BIconBagCheck extends BvComponent {}

export declare class BIconBagCheckFill extends BvComponent {}

export declare class BIconBagDash extends BvComponent {}

export declare class BIconBagDashFill extends BvComponent {}

export declare class BIconBagFill extends BvComponent {}

export declare class BIconBagPlus extends BvComponent {}

export declare class BIconBagPlusFill extends BvComponent {}

export declare class BIconBagX extends BvComponent {}

export declare class BIconBagXFill extends BvComponent {}

export declare class BIconBarChart extends BvComponent {}

export declare class BIconBarChartFill extends BvComponent {}

export declare class BIconBarChartLine extends BvComponent {}

export declare class BIconBarChartLineFill extends BvComponent {}

export declare class BIconBarChartSteps extends BvComponent {}

export declare class BIconBasket extends BvComponent {}

export declare class BIconBasket2 extends BvComponent {}

export declare class BIconBasket2Fill extends BvComponent {}

export declare class BIconBasket3 extends BvComponent {}

export declare class BIconBasket3Fill extends BvComponent {}

export declare class BIconBasketFill extends BvComponent {}

export declare class BIconBattery extends BvComponent {}

export declare class BIconBatteryCharging extends BvComponent {}

export declare class BIconBatteryFull extends BvComponent {}

export declare class BIconBatteryHalf extends BvComponent {}

export declare class BIconBell extends BvComponent {}

export declare class BIconBellFill extends BvComponent {}

export declare class BIconBezier extends BvComponent {}

export declare class BIconBezier2 extends BvComponent {}

export declare class BIconBicycle extends BvComponent {}

export declare class BIconBinoculars extends BvComponent {}

export declare class BIconBinocularsFill extends BvComponent {}

export declare class BIconBlockquoteLeft extends BvComponent {}

export declare class BIconBlockquoteRight extends BvComponent {}

export declare class BIconBook extends BvComponent {}

export declare class BIconBookFill extends BvComponent {}

export declare class BIconBookHalf extends BvComponent {}

export declare class BIconBookmark extends BvComponent {}

export declare class BIconBookmarkCheck extends BvComponent {}

export declare class BIconBookmarkCheckFill extends BvComponent {}

export declare class BIconBookmarkDash extends BvComponent {}

export declare class BIconBookmarkDashFill extends BvComponent {}

export declare class BIconBookmarkFill extends BvComponent {}

export declare class BIconBookmarkHeart extends BvComponent {}

export declare class BIconBookmarkHeartFill extends BvComponent {}

export declare class BIconBookmarkPlus extends BvComponent {}

export declare class BIconBookmarkPlusFill extends BvComponent {}

export declare class BIconBookmarkStar extends BvComponent {}

export declare class BIconBookmarkStarFill extends BvComponent {}

export declare class BIconBookmarkX extends BvComponent {}

export declare class BIconBookmarkXFill extends BvComponent {}

export declare class BIconBookmarks extends BvComponent {}

export declare class BIconBookmarksFill extends BvComponent {}

export declare class BIconBookshelf extends BvComponent {}

export declare class BIconBootstrap extends BvComponent {}

export declare class BIconBootstrapFill extends BvComponent {}

export declare class BIconBootstrapReboot extends BvComponent {}

export declare class BIconBorderStyle extends BvComponent {}

export declare class BIconBorderWidth extends BvComponent {}

export declare class BIconBoundingBox extends BvComponent {}

export declare class BIconBoundingBoxCircles extends BvComponent {}

export declare class BIconBox extends BvComponent {}

export declare class BIconBoxArrowDown extends BvComponent {}

export declare class BIconBoxArrowDownLeft extends BvComponent {}

export declare class BIconBoxArrowDownRight extends BvComponent {}

export declare class BIconBoxArrowInDown extends BvComponent {}

export declare class BIconBoxArrowInDownLeft extends BvComponent {}

export declare class BIconBoxArrowInDownRight extends BvComponent {}

export declare class BIconBoxArrowInLeft extends BvComponent {}

export declare class BIconBoxArrowInRight extends BvComponent {}

export declare class BIconBoxArrowInUp extends BvComponent {}

export declare class BIconBoxArrowInUpLeft extends BvComponent {}

export declare class BIconBoxArrowInUpRight extends BvComponent {}

export declare class BIconBoxArrowLeft extends BvComponent {}

export declare class BIconBoxArrowRight extends BvComponent {}

export declare class BIconBoxArrowUp extends BvComponent {}

export declare class BIconBoxArrowUpLeft extends BvComponent {}

export declare class BIconBoxArrowUpRight extends BvComponent {}

export declare class BIconBoxSeam extends BvComponent {}

export declare class BIconBraces extends BvComponent {}

export declare class BIconBricks extends BvComponent {}

export declare class BIconBriefcase extends BvComponent {}

export declare class BIconBriefcaseFill extends BvComponent {}

export declare class BIconBrightnessAltHigh extends BvComponent {}

export declare class BIconBrightnessAltHighFill extends BvComponent {}

export declare class BIconBrightnessAltLow extends BvComponent {}

export declare class BIconBrightnessAltLowFill extends BvComponent {}

export declare class BIconBrightnessHigh extends BvComponent {}

export declare class BIconBrightnessHighFill extends BvComponent {}

export declare class BIconBrightnessLow extends BvComponent {}

export declare class BIconBrightnessLowFill extends BvComponent {}

export declare class BIconBroadcast extends BvComponent {}

export declare class BIconBroadcastPin extends BvComponent {}

export declare class BIconBrush extends BvComponent {}

export declare class BIconBrushFill extends BvComponent {}

export declare class BIconBucket extends BvComponent {}

export declare class BIconBucketFill extends BvComponent {}

export declare class BIconBug extends BvComponent {}

export declare class BIconBugFill extends BvComponent {}

export declare class BIconBuilding extends BvComponent {}

export declare class BIconBullseye extends BvComponent {}

export declare class BIconCalculator extends BvComponent {}

export declare class BIconCalculatorFill extends BvComponent {}

export declare class BIconCalendar extends BvComponent {}

export declare class BIconCalendar2 extends BvComponent {}

export declare class BIconCalendar2Check extends BvComponent {}

export declare class BIconCalendar2CheckFill extends BvComponent {}

export declare class BIconCalendar2Date extends BvComponent {}

export declare class BIconCalendar2DateFill extends BvComponent {}

export declare class BIconCalendar2Day extends BvComponent {}

export declare class BIconCalendar2DayFill extends BvComponent {}

export declare class BIconCalendar2Event extends BvComponent {}

export declare class BIconCalendar2EventFill extends BvComponent {}

export declare class BIconCalendar2Fill extends BvComponent {}

export declare class BIconCalendar2Minus extends BvComponent {}

export declare class BIconCalendar2MinusFill extends BvComponent {}

export declare class BIconCalendar2Month extends BvComponent {}

export declare class BIconCalendar2MonthFill extends BvComponent {}

export declare class BIconCalendar2Plus extends BvComponent {}

export declare class BIconCalendar2PlusFill extends BvComponent {}

export declare class BIconCalendar2Range extends BvComponent {}

export declare class BIconCalendar2RangeFill extends BvComponent {}

export declare class BIconCalendar2Week extends BvComponent {}

export declare class BIconCalendar2WeekFill extends BvComponent {}

export declare class BIconCalendar2X extends BvComponent {}

export declare class BIconCalendar2XFill extends BvComponent {}

export declare class BIconCalendar3 extends BvComponent {}

export declare class BIconCalendar3Event extends BvComponent {}

export declare class BIconCalendar3EventFill extends BvComponent {}

export declare class BIconCalendar3Fill extends BvComponent {}

export declare class BIconCalendar3Range extends BvComponent {}

export declare class BIconCalendar3RangeFill extends BvComponent {}

export declare class BIconCalendar3Week extends BvComponent {}

export declare class BIconCalendar3WeekFill extends BvComponent {}

export declare class BIconCalendar4 extends BvComponent {}

export declare class BIconCalendar4Event extends BvComponent {}

export declare class BIconCalendar4Range extends BvComponent {}

export declare class BIconCalendar4Week extends BvComponent {}

export declare class BIconCalendarCheck extends BvComponent {}

export declare class BIconCalendarCheckFill extends BvComponent {}

export declare class BIconCalendarDate extends BvComponent {}

export declare class BIconCalendarDateFill extends BvComponent {}

export declare class BIconCalendarDay extends BvComponent {}

export declare class BIconCalendarDayFill extends BvComponent {}

export declare class BIconCalendarEvent extends BvComponent {}

export declare class BIconCalendarEventFill extends BvComponent {}

export declare class BIconCalendarFill extends BvComponent {}

export declare class BIconCalendarMinus extends BvComponent {}

export declare class BIconCalendarMinusFill extends BvComponent {}

export declare class BIconCalendarMonth extends BvComponent {}

export declare class BIconCalendarMonthFill extends BvComponent {}

export declare class BIconCalendarPlus extends BvComponent {}

export declare class BIconCalendarPlusFill extends BvComponent {}

export declare class BIconCalendarRange extends BvComponent {}

export declare class BIconCalendarRangeFill extends BvComponent {}

export declare class BIconCalendarWeek extends BvComponent {}

export declare class BIconCalendarWeekFill extends BvComponent {}

export declare class BIconCalendarX extends BvComponent {}

export declare class BIconCalendarXFill extends BvComponent {}

export declare class BIconCamera extends BvComponent {}

export declare class BIconCamera2 extends BvComponent {}

export declare class BIconCameraFill extends BvComponent {}

export declare class BIconCameraReels extends BvComponent {}

export declare class BIconCameraReelsFill extends BvComponent {}

export declare class BIconCameraVideo extends BvComponent {}

export declare class BIconCameraVideoFill extends BvComponent {}

export declare class BIconCameraVideoOff extends BvComponent {}

export declare class BIconCameraVideoOffFill extends BvComponent {}

export declare class BIconCapslock extends BvComponent {}

export declare class BIconCapslockFill extends BvComponent {}

export declare class BIconCardChecklist extends BvComponent {}

export declare class BIconCardHeading extends BvComponent {}

export declare class BIconCardImage extends BvComponent {}

export declare class BIconCardList extends BvComponent {}

export declare class BIconCardText extends BvComponent {}

export declare class BIconCaretDown extends BvComponent {}

export declare class BIconCaretDownFill extends BvComponent {}

export declare class BIconCaretDownSquare extends BvComponent {}

export declare class BIconCaretDownSquareFill extends BvComponent {}

export declare class BIconCaretLeft extends BvComponent {}

export declare class BIconCaretLeftFill extends BvComponent {}

export declare class BIconCaretLeftSquare extends BvComponent {}

export declare class BIconCaretLeftSquareFill extends BvComponent {}

export declare class BIconCaretRight extends BvComponent {}

export declare class BIconCaretRightFill extends BvComponent {}

export declare class BIconCaretRightSquare extends BvComponent {}

export declare class BIconCaretRightSquareFill extends BvComponent {}

export declare class BIconCaretUp extends BvComponent {}

export declare class BIconCaretUpFill extends BvComponent {}

export declare class BIconCaretUpSquare extends BvComponent {}

export declare class BIconCaretUpSquareFill extends BvComponent {}

export declare class BIconCart extends BvComponent {}

export declare class BIconCart2 extends BvComponent {}

export declare class BIconCart3 extends BvComponent {}

export declare class BIconCart4 extends BvComponent {}

export declare class BIconCartCheck extends BvComponent {}

export declare class BIconCartCheckFill extends BvComponent {}

export declare class BIconCartDash extends BvComponent {}

export declare class BIconCartDashFill extends BvComponent {}

export declare class BIconCartFill extends BvComponent {}

export declare class BIconCartPlus extends BvComponent {}

export declare class BIconCartPlusFill extends BvComponent {}

export declare class BIconCartX extends BvComponent {}

export declare class BIconCartXFill extends BvComponent {}

export declare class BIconCash extends BvComponent {}

export declare class BIconCashStack extends BvComponent {}

export declare class BIconCast extends BvComponent {}

export declare class BIconChat extends BvComponent {}

export declare class BIconChatDots extends BvComponent {}

export declare class BIconChatDotsFill extends BvComponent {}

export declare class BIconChatFill extends BvComponent {}

export declare class BIconChatLeft extends BvComponent {}

export declare class BIconChatLeftDots extends BvComponent {}

export declare class BIconChatLeftDotsFill extends BvComponent {}

export declare class BIconChatLeftFill extends BvComponent {}

export declare class BIconChatLeftQuote extends BvComponent {}

export declare class BIconChatLeftQuoteFill extends BvComponent {}

export declare class BIconChatLeftText extends BvComponent {}

export declare class BIconChatLeftTextFill extends BvComponent {}

export declare class BIconChatQuote extends BvComponent {}

export declare class BIconChatQuoteFill extends BvComponent {}

export declare class BIconChatRight extends BvComponent {}

export declare class BIconChatRightDots extends BvComponent {}

export declare class BIconChatRightDotsFill extends BvComponent {}

export declare class BIconChatRightFill extends BvComponent {}

export declare class BIconChatRightQuote extends BvComponent {}

export declare class BIconChatRightQuoteFill extends BvComponent {}

export declare class BIconChatRightText extends BvComponent {}

export declare class BIconChatRightTextFill extends BvComponent {}

export declare class BIconChatSquare extends BvComponent {}

export declare class BIconChatSquareDots extends BvComponent {}

export declare class BIconChatSquareDotsFill extends BvComponent {}

export declare class BIconChatSquareFill extends BvComponent {}

export declare class BIconChatSquareQuote extends BvComponent {}

export declare class BIconChatSquareQuoteFill extends BvComponent {}

export declare class BIconChatSquareText extends BvComponent {}

export declare class BIconChatSquareTextFill extends BvComponent {}

export declare class BIconChatText extends BvComponent {}

export declare class BIconChatTextFill extends BvComponent {}

export declare class BIconCheck extends BvComponent {}

export declare class BIconCheck2 extends BvComponent {}

export declare class BIconCheck2All extends BvComponent {}

export declare class BIconCheck2Circle extends BvComponent {}

export declare class BIconCheck2Square extends BvComponent {}

export declare class BIconCheckAll extends BvComponent {}

export declare class BIconCheckCircle extends BvComponent {}

export declare class BIconCheckCircleFill extends BvComponent {}

export declare class BIconCheckSquare extends BvComponent {}

export declare class BIconCheckSquareFill extends BvComponent {}

export declare class BIconChevronBarContract extends BvComponent {}

export declare class BIconChevronBarDown extends BvComponent {}

export declare class BIconChevronBarExpand extends BvComponent {}

export declare class BIconChevronBarLeft extends BvComponent {}

export declare class BIconChevronBarRight extends BvComponent {}

export declare class BIconChevronBarUp extends BvComponent {}

export declare class BIconChevronCompactDown extends BvComponent {}

export declare class BIconChevronCompactLeft extends BvComponent {}

export declare class BIconChevronCompactRight extends BvComponent {}

export declare class BIconChevronCompactUp extends BvComponent {}

export declare class BIconChevronContract extends BvComponent {}

export declare class BIconChevronDoubleDown extends BvComponent {}

export declare class BIconChevronDoubleLeft extends BvComponent {}

export declare class BIconChevronDoubleRight extends BvComponent {}

export declare class BIconChevronDoubleUp extends BvComponent {}

export declare class BIconChevronDown extends BvComponent {}

export declare class BIconChevronExpand extends BvComponent {}

export declare class BIconChevronLeft extends BvComponent {}

export declare class BIconChevronRight extends BvComponent {}

export declare class BIconChevronUp extends BvComponent {}

export declare class BIconCircle extends BvComponent {}

export declare class BIconCircleFill extends BvComponent {}

export declare class BIconCircleHalf extends BvComponent {}

export declare class BIconCircleSquare extends BvComponent {}

export declare class BIconClipboard extends BvComponent {}

export declare class BIconClipboardCheck extends BvComponent {}

export declare class BIconClipboardData extends BvComponent {}

export declare class BIconClipboardMinus extends BvComponent {}

export declare class BIconClipboardPlus extends BvComponent {}

export declare class BIconClipboardX extends BvComponent {}

export declare class BIconClock extends BvComponent {}

export declare class BIconClockFill extends BvComponent {}

export declare class BIconClockHistory extends BvComponent {}

export declare class BIconCloud extends BvComponent {}

export declare class BIconCloudArrowDown extends BvComponent {}

export declare class BIconCloudArrowDownFill extends BvComponent {}

export declare class BIconCloudArrowUp extends BvComponent {}

export declare class BIconCloudArrowUpFill extends BvComponent {}

export declare class BIconCloudCheck extends BvComponent {}

export declare class BIconCloudCheckFill extends BvComponent {}

export declare class BIconCloudDownload extends BvComponent {}

export declare class BIconCloudDownloadFill extends BvComponent {}

export declare class BIconCloudFill extends BvComponent {}

export declare class BIconCloudMinus extends BvComponent {}

export declare class BIconCloudMinusFill extends BvComponent {}

export declare class BIconCloudPlus extends BvComponent {}

export declare class BIconCloudPlusFill extends BvComponent {}

export declare class BIconCloudSlash extends BvComponent {}

export declare class BIconCloudSlashFill extends BvComponent {}

export declare class BIconCloudUpload extends BvComponent {}

export declare class BIconCloudUploadFill extends BvComponent {}

export declare class BIconCode extends BvComponent {}

export declare class BIconCodeSlash extends BvComponent {}

export declare class BIconCodeSquare extends BvComponent {}

export declare class BIconCollection extends BvComponent {}

export declare class BIconCollectionFill extends BvComponent {}

export declare class BIconCollectionPlay extends BvComponent {}

export declare class BIconCollectionPlayFill extends BvComponent {}

export declare class BIconColumns extends BvComponent {}

export declare class BIconColumnsGap extends BvComponent {}

export declare class BIconCommand extends BvComponent {}

export declare class BIconCompass extends BvComponent {}

export declare class BIconCompassFill extends BvComponent {}

export declare class BIconCone extends BvComponent {}

export declare class BIconConeStriped extends BvComponent {}

export declare class BIconController extends BvComponent {}

export declare class BIconCpu extends BvComponent {}

export declare class BIconCpuFill extends BvComponent {}

export declare class BIconCreditCard extends BvComponent {}

export declare class BIconCreditCard2Back extends BvComponent {}

export declare class BIconCreditCard2BackFill extends BvComponent {}

export declare class BIconCreditCard2Front extends BvComponent {}

export declare class BIconCreditCard2FrontFill extends BvComponent {}

export declare class BIconCreditCardFill extends BvComponent {}

export declare class BIconCrop extends BvComponent {}

export declare class BIconCup extends BvComponent {}

export declare class BIconCupFill extends BvComponent {}

export declare class BIconCupStraw extends BvComponent {}

export declare class BIconCursor extends BvComponent {}

export declare class BIconCursorFill extends BvComponent {}

export declare class BIconCursorText extends BvComponent {}

export declare class BIconDash extends BvComponent {}

export declare class BIconDashCircle extends BvComponent {}

export declare class BIconDashCircleFill extends BvComponent {}

export declare class BIconDashSquare extends BvComponent {}

export declare class BIconDashSquareFill extends BvComponent {}

export declare class BIconDiagram2 extends BvComponent {}

export declare class BIconDiagram2Fill extends BvComponent {}

export declare class BIconDiagram3 extends BvComponent {}

export declare class BIconDiagram3Fill extends BvComponent {}

export declare class BIconDiamond extends BvComponent {}

export declare class BIconDiamondFill extends BvComponent {}

export declare class BIconDiamondHalf extends BvComponent {}

export declare class BIconDice1 extends BvComponent {}

export declare class BIconDice1Fill extends BvComponent {}

export declare class BIconDice2 extends BvComponent {}

export declare class BIconDice2Fill extends BvComponent {}

export declare class BIconDice3 extends BvComponent {}

export declare class BIconDice3Fill extends BvComponent {}

export declare class BIconDice4 extends BvComponent {}

export declare class BIconDice4Fill extends BvComponent {}

export declare class BIconDice5 extends BvComponent {}

export declare class BIconDice5Fill extends BvComponent {}

export declare class BIconDice6 extends BvComponent {}

export declare class BIconDice6Fill extends BvComponent {}

export declare class BIconDisc extends BvComponent {}

export declare class BIconDiscFill extends BvComponent {}

export declare class BIconDiscord extends BvComponent {}

export declare class BIconDisplay extends BvComponent {}

export declare class BIconDisplayFill extends BvComponent {}

export declare class BIconDistributeHorizontal extends BvComponent {}

export declare class BIconDistributeVertical extends BvComponent {}

export declare class BIconDoorClosed extends BvComponent {}

export declare class BIconDoorClosedFill extends BvComponent {}

export declare class BIconDoorOpen extends BvComponent {}

export declare class BIconDoorOpenFill extends BvComponent {}

export declare class BIconDot extends BvComponent {}

export declare class BIconDownload extends BvComponent {}

export declare class BIconDroplet extends BvComponent {}

export declare class BIconDropletFill extends BvComponent {}

export declare class BIconDropletHalf extends BvComponent {}

export declare class BIconEarbuds extends BvComponent {}

export declare class BIconEasel extends BvComponent {}

export declare class BIconEaselFill extends BvComponent {}

export declare class BIconEgg extends BvComponent {}

export declare class BIconEggFill extends BvComponent {}

export declare class BIconEggFried extends BvComponent {}

export declare class BIconEject extends BvComponent {}

export declare class BIconEjectFill extends BvComponent {}

export declare class BIconEmojiAngry extends BvComponent {}

export declare class BIconEmojiAngryFill extends BvComponent {}

export declare class BIconEmojiDizzy extends BvComponent {}

export declare class BIconEmojiDizzyFill extends BvComponent {}

export declare class BIconEmojiExpressionless extends BvComponent {}

export declare class BIconEmojiExpressionlessFill extends BvComponent {}

export declare class BIconEmojiFrown extends BvComponent {}

export declare class BIconEmojiFrownFill extends BvComponent {}

export declare class BIconEmojiHeartEyes extends BvComponent {}

export declare class BIconEmojiHeartEyesFill extends BvComponent {}

export declare class BIconEmojiLaughing extends BvComponent {}

export declare class BIconEmojiLaughingFill extends BvComponent {}

export declare class BIconEmojiNeutral extends BvComponent {}

export declare class BIconEmojiNeutralFill extends BvComponent {}

export declare class BIconEmojiSmile extends BvComponent {}

export declare class BIconEmojiSmileFill extends BvComponent {}

export declare class BIconEmojiSmileUpsideDown extends BvComponent {}

export declare class BIconEmojiSmileUpsideDownFill extends BvComponent {}

export declare class BIconEmojiSunglasses extends BvComponent {}

export declare class BIconEmojiSunglassesFill extends BvComponent {}

export declare class BIconEmojiWink extends BvComponent {}

export declare class BIconEmojiWinkFill extends BvComponent {}

export declare class BIconEnvelope extends BvComponent {}

export declare class BIconEnvelopeFill extends BvComponent {}

export declare class BIconEnvelopeOpen extends BvComponent {}

export declare class BIconEnvelopeOpenFill extends BvComponent {}

export declare class BIconExclamation extends BvComponent {}

export declare class BIconExclamationCircle extends BvComponent {}

export declare class BIconExclamationCircleFill extends BvComponent {}

export declare class BIconExclamationDiamond extends BvComponent {}

export declare class BIconExclamationDiamondFill extends BvComponent {}

export declare class BIconExclamationOctagon extends BvComponent {}

export declare class BIconExclamationOctagonFill extends BvComponent {}

export declare class BIconExclamationSquare extends BvComponent {}

export declare class BIconExclamationSquareFill extends BvComponent {}

export declare class BIconExclamationTriangle extends BvComponent {}

export declare class BIconExclamationTriangleFill extends BvComponent {}

export declare class BIconExclude extends BvComponent {}

export declare class BIconEye extends BvComponent {}

export declare class BIconEyeFill extends BvComponent {}

export declare class BIconEyeSlash extends BvComponent {}

export declare class BIconEyeSlashFill extends BvComponent {}

export declare class BIconEyeglasses extends BvComponent {}

export declare class BIconFacebook extends BvComponent {}

export declare class BIconFile extends BvComponent {}

export declare class BIconFileArrowDown extends BvComponent {}

export declare class BIconFileArrowDownFill extends BvComponent {}

export declare class BIconFileArrowUp extends BvComponent {}

export declare class BIconFileArrowUpFill extends BvComponent {}

export declare class BIconFileBarGraph extends BvComponent {}

export declare class BIconFileBarGraphFill extends BvComponent {}

export declare class BIconFileBinary extends BvComponent {}

export declare class BIconFileBinaryFill extends BvComponent {}

export declare class BIconFileBreak extends BvComponent {}

export declare class BIconFileBreakFill extends BvComponent {}

export declare class BIconFileCheck extends BvComponent {}

export declare class BIconFileCheckFill extends BvComponent {}

export declare class BIconFileCode extends BvComponent {}

export declare class BIconFileCodeFill extends BvComponent {}

export declare class BIconFileDiff extends BvComponent {}

export declare class BIconFileDiffFill extends BvComponent {}

export declare class BIconFileEarmark extends BvComponent {}

export declare class BIconFileEarmarkArrowDown extends BvComponent {}

export declare class BIconFileEarmarkArrowDownFill extends BvComponent {}

export declare class BIconFileEarmarkArrowUp extends BvComponent {}

export declare class BIconFileEarmarkArrowUpFill extends BvComponent {}

export declare class BIconFileEarmarkBarGraph extends BvComponent {}

export declare class BIconFileEarmarkBarGraphFill extends BvComponent {}

export declare class BIconFileEarmarkBinary extends BvComponent {}

export declare class BIconFileEarmarkBinaryFill extends BvComponent {}

export declare class BIconFileEarmarkBreak extends BvComponent {}

export declare class BIconFileEarmarkBreakFill extends BvComponent {}

export declare class BIconFileEarmarkCheck extends BvComponent {}

export declare class BIconFileEarmarkCheckFill extends BvComponent {}

export declare class BIconFileEarmarkCode extends BvComponent {}

export declare class BIconFileEarmarkCodeFill extends BvComponent {}

export declare class BIconFileEarmarkDiff extends BvComponent {}

export declare class BIconFileEarmarkDiffFill extends BvComponent {}

export declare class BIconFileEarmarkEasel extends BvComponent {}

export declare class BIconFileEarmarkEaselFill extends BvComponent {}

export declare class BIconFileEarmarkExcel extends BvComponent {}

export declare class BIconFileEarmarkExcelFill extends BvComponent {}

export declare class BIconFileEarmarkFill extends BvComponent {}

export declare class BIconFileEarmarkFont extends BvComponent {}

export declare class BIconFileEarmarkFontFill extends BvComponent {}

export declare class BIconFileEarmarkImage extends BvComponent {}

export declare class BIconFileEarmarkImageFill extends BvComponent {}

export declare class BIconFileEarmarkLock extends BvComponent {}

export declare class BIconFileEarmarkLock2 extends BvComponent {}

export declare class BIconFileEarmarkLock2Fill extends BvComponent {}

export declare class BIconFileEarmarkLockFill extends BvComponent {}

export declare class BIconFileEarmarkMedical extends BvComponent {}

export declare class BIconFileEarmarkMedicalFill extends BvComponent {}

export declare class BIconFileEarmarkMinus extends BvComponent {}

export declare class BIconFileEarmarkMinusFill extends BvComponent {}

export declare class BIconFileEarmarkMusic extends BvComponent {}

export declare class BIconFileEarmarkMusicFill extends BvComponent {}

export declare class BIconFileEarmarkPerson extends BvComponent {}

export declare class BIconFileEarmarkPersonFill extends BvComponent {}

export declare class BIconFileEarmarkPlay extends BvComponent {}

export declare class BIconFileEarmarkPlayFill extends BvComponent {}

export declare class BIconFileEarmarkPlus extends BvComponent {}

export declare class BIconFileEarmarkPlusFill extends BvComponent {}

export declare class BIconFileEarmarkPost extends BvComponent {}

export declare class BIconFileEarmarkPostFill extends BvComponent {}

export declare class BIconFileEarmarkPpt extends BvComponent {}

export declare class BIconFileEarmarkPptFill extends BvComponent {}

export declare class BIconFileEarmarkRichtext extends BvComponent {}

export declare class BIconFileEarmarkRichtextFill extends BvComponent {}

export declare class BIconFileEarmarkRuled extends BvComponent {}

export declare class BIconFileEarmarkRuledFill extends BvComponent {}

export declare class BIconFileEarmarkSlides extends BvComponent {}

export declare class BIconFileEarmarkSlidesFill extends BvComponent {}

export declare class BIconFileEarmarkSpreadsheet extends BvComponent {}

export declare class BIconFileEarmarkSpreadsheetFill extends BvComponent {}

export declare class BIconFileEarmarkText extends BvComponent {}

export declare class BIconFileEarmarkTextFill extends BvComponent {}

export declare class BIconFileEarmarkWord extends BvComponent {}

export declare class BIconFileEarmarkWordFill extends BvComponent {}

export declare class BIconFileEarmarkX extends BvComponent {}

export declare class BIconFileEarmarkXFill extends BvComponent {}

export declare class BIconFileEarmarkZip extends BvComponent {}

export declare class BIconFileEarmarkZipFill extends BvComponent {}

export declare class BIconFileEasel extends BvComponent {}

export declare class BIconFileEaselFill extends BvComponent {}

export declare class BIconFileExcel extends BvComponent {}

export declare class BIconFileExcelFill extends BvComponent {}

export declare class BIconFileFill extends BvComponent {}

export declare class BIconFileFont extends BvComponent {}

export declare class BIconFileFontFill extends BvComponent {}

export declare class BIconFileImage extends BvComponent {}

export declare class BIconFileImageFill extends BvComponent {}

export declare class BIconFileLock extends BvComponent {}

export declare class BIconFileLock2 extends BvComponent {}

export declare class BIconFileLock2Fill extends BvComponent {}

export declare class BIconFileLockFill extends BvComponent {}

export declare class BIconFileMedical extends BvComponent {}

export declare class BIconFileMedicalFill extends BvComponent {}

export declare class BIconFileMinus extends BvComponent {}

export declare class BIconFileMinusFill extends BvComponent {}

export declare class BIconFileMusic extends BvComponent {}

export declare class BIconFileMusicFill extends BvComponent {}

export declare class BIconFilePerson extends BvComponent {}

export declare class BIconFilePersonFill extends BvComponent {}

export declare class BIconFilePlay extends BvComponent {}

export declare class BIconFilePlayFill extends BvComponent {}

export declare class BIconFilePlus extends BvComponent {}

export declare class BIconFilePlusFill extends BvComponent {}

export declare class BIconFilePost extends BvComponent {}

export declare class BIconFilePostFill extends BvComponent {}

export declare class BIconFilePpt extends BvComponent {}

export declare class BIconFilePptFill extends BvComponent {}

export declare class BIconFileRichtext extends BvComponent {}

export declare class BIconFileRichtextFill extends BvComponent {}

export declare class BIconFileRuled extends BvComponent {}

export declare class BIconFileRuledFill extends BvComponent {}

export declare class BIconFileSlides extends BvComponent {}

export declare class BIconFileSlidesFill extends BvComponent {}

export declare class BIconFileSpreadsheet extends BvComponent {}

export declare class BIconFileSpreadsheetFill extends BvComponent {}

export declare class BIconFileText extends BvComponent {}

export declare class BIconFileTextFill extends BvComponent {}

export declare class BIconFileWord extends BvComponent {}

export declare class BIconFileWordFill extends BvComponent {}

export declare class BIconFileX extends BvComponent {}

export declare class BIconFileXFill extends BvComponent {}

export declare class BIconFileZip extends BvComponent {}

export declare class BIconFileZipFill extends BvComponent {}

export declare class BIconFiles extends BvComponent {}

export declare class BIconFilesAlt extends BvComponent {}

export declare class BIconFilm extends BvComponent {}

export declare class BIconFilter extends BvComponent {}

export declare class BIconFilterCircle extends BvComponent {}

export declare class BIconFilterCircleFill extends BvComponent {}

export declare class BIconFilterLeft extends BvComponent {}

export declare class BIconFilterRight extends BvComponent {}

export declare class BIconFilterSquare extends BvComponent {}

export declare class BIconFilterSquareFill extends BvComponent {}

export declare class BIconFlag extends BvComponent {}

export declare class BIconFlagFill extends BvComponent {}

export declare class BIconFlower1 extends BvComponent {}

export declare class BIconFlower2 extends BvComponent {}

export declare class BIconFlower3 extends BvComponent {}

export declare class BIconFolder extends BvComponent {}

export declare class BIconFolder2 extends BvComponent {}

export declare class BIconFolder2Open extends BvComponent {}

export declare class BIconFolderCheck extends BvComponent {}

export declare class BIconFolderFill extends BvComponent {}

export declare class BIconFolderMinus extends BvComponent {}

export declare class BIconFolderPlus extends BvComponent {}

export declare class BIconFolderSymlink extends BvComponent {}

export declare class BIconFolderSymlinkFill extends BvComponent {}

export declare class BIconFolderX extends BvComponent {}

export declare class BIconFonts extends BvComponent {}

export declare class BIconForward extends BvComponent {}

export declare class BIconForwardFill extends BvComponent {}

export declare class BIconFront extends BvComponent {}

export declare class BIconFullscreen extends BvComponent {}

export declare class BIconFullscreenExit extends BvComponent {}

export declare class BIconFunnel extends BvComponent {}

export declare class BIconFunnelFill extends BvComponent {}

export declare class BIconGear extends BvComponent {}

export declare class BIconGearFill extends BvComponent {}

export declare class BIconGearWide extends BvComponent {}

export declare class BIconGearWideConnected extends BvComponent {}

export declare class BIconGem extends BvComponent {}

export declare class BIconGeo extends BvComponent {}

export declare class BIconGeoAlt extends BvComponent {}

export declare class BIconGeoAltFill extends BvComponent {}

export declare class BIconGeoFill extends BvComponent {}

export declare class BIconGift extends BvComponent {}

export declare class BIconGiftFill extends BvComponent {}

export declare class BIconGithub extends BvComponent {}

export declare class BIconGlobe extends BvComponent {}

export declare class BIconGlobe2 extends BvComponent {}

export declare class BIconGoogle extends BvComponent {}

export declare class BIconGraphDown extends BvComponent {}

export declare class BIconGraphUp extends BvComponent {}

export declare class BIconGrid extends BvComponent {}

export declare class BIconGrid1x2 extends BvComponent {}

export declare class BIconGrid1x2Fill extends BvComponent {}

export declare class BIconGrid3x2 extends BvComponent {}

export declare class BIconGrid3x2Gap extends BvComponent {}

export declare class BIconGrid3x2GapFill extends BvComponent {}

export declare class BIconGrid3x3 extends BvComponent {}

export declare class BIconGrid3x3Gap extends BvComponent {}

export declare class BIconGrid3x3GapFill extends BvComponent {}

export declare class BIconGridFill extends BvComponent {}

export declare class BIconGripHorizontal extends BvComponent {}

export declare class BIconGripVertical extends BvComponent {}

export declare class BIconHammer extends BvComponent {}

export declare class BIconHandIndex extends BvComponent {}

export declare class BIconHandIndexThumb extends BvComponent {}

export declare class BIconHandThumbsDown extends BvComponent {}

export declare class BIconHandThumbsUp extends BvComponent {}

export declare class BIconHandbag extends BvComponent {}

export declare class BIconHandbagFill extends BvComponent {}

export declare class BIconHash extends BvComponent {}

export declare class BIconHdd extends BvComponent {}

export declare class BIconHddFill extends BvComponent {}

export declare class BIconHddNetwork extends BvComponent {}

export declare class BIconHddNetworkFill extends BvComponent {}

export declare class BIconHddRack extends BvComponent {}

export declare class BIconHddRackFill extends BvComponent {}

export declare class BIconHddStack extends BvComponent {}

export declare class BIconHddStackFill extends BvComponent {}

export declare class BIconHeadphones extends BvComponent {}

export declare class BIconHeadset extends BvComponent {}

export declare class BIconHeart extends BvComponent {}

export declare class BIconHeartFill extends BvComponent {}

export declare class BIconHeartHalf extends BvComponent {}

export declare class BIconHeptagon extends BvComponent {}

export declare class BIconHeptagonFill extends BvComponent {}

export declare class BIconHeptagonHalf extends BvComponent {}

export declare class BIconHexagon extends BvComponent {}

export declare class BIconHexagonFill extends BvComponent {}

export declare class BIconHexagonHalf extends BvComponent {}

export declare class BIconHourglass extends BvComponent {}

export declare class BIconHourglassBottom extends BvComponent {}

export declare class BIconHourglassSplit extends BvComponent {}

export declare class BIconHourglassTop extends BvComponent {}

export declare class BIconHouse extends BvComponent {}

export declare class BIconHouseDoor extends BvComponent {}

export declare class BIconHouseDoorFill extends BvComponent {}

export declare class BIconHouseFill extends BvComponent {}

export declare class BIconHr extends BvComponent {}

export declare class BIconImage extends BvComponent {}

export declare class BIconImageAlt extends BvComponent {}

export declare class BIconImageFill extends BvComponent {}

export declare class BIconImages extends BvComponent {}

export declare class BIconInbox extends BvComponent {}

export declare class BIconInboxFill extends BvComponent {}

export declare class BIconInboxes extends BvComponent {}

export declare class BIconInboxesFill extends BvComponent {}

export declare class BIconInfo extends BvComponent {}

export declare class BIconInfoCircle extends BvComponent {}

export declare class BIconInfoCircleFill extends BvComponent {}

export declare class BIconInfoSquare extends BvComponent {}

export declare class BIconInfoSquareFill extends BvComponent {}

export declare class BIconInputCursor extends BvComponent {}

export declare class BIconInputCursorText extends BvComponent {}

export declare class BIconInstagram extends BvComponent {}

export declare class BIconIntersect extends BvComponent {}

export declare class BIconJournal extends BvComponent {}

export declare class BIconJournalAlbum extends BvComponent {}

export declare class BIconJournalArrowDown extends BvComponent {}

export declare class BIconJournalArrowUp extends BvComponent {}

export declare class BIconJournalBookmark extends BvComponent {}

export declare class BIconJournalBookmarkFill extends BvComponent {}

export declare class BIconJournalCheck extends BvComponent {}

export declare class BIconJournalCode extends BvComponent {}

export declare class BIconJournalMedical extends BvComponent {}

export declare class BIconJournalMinus extends BvComponent {}

export declare class BIconJournalPlus extends BvComponent {}

export declare class BIconJournalRichtext extends BvComponent {}

export declare class BIconJournalText extends BvComponent {}

export declare class BIconJournalX extends BvComponent {}

export declare class BIconJournals extends BvComponent {}

export declare class BIconJoystick extends BvComponent {}

export declare class BIconJustify extends BvComponent {}

export declare class BIconJustifyLeft extends BvComponent {}

export declare class BIconJustifyRight extends BvComponent {}

export declare class BIconKanban extends BvComponent {}

export declare class BIconKanbanFill extends BvComponent {}

export declare class BIconKey extends BvComponent {}

export declare class BIconKeyFill extends BvComponent {}

export declare class BIconKeyboard extends BvComponent {}

export declare class BIconKeyboardFill extends BvComponent {}

export declare class BIconLadder extends BvComponent {}

export declare class BIconLamp extends BvComponent {}

export declare class BIconLampFill extends BvComponent {}

export declare class BIconLaptop extends BvComponent {}

export declare class BIconLaptopFill extends BvComponent {}

export declare class BIconLayers extends BvComponent {}

export declare class BIconLayersFill extends BvComponent {}

export declare class BIconLayersHalf extends BvComponent {}

export declare class BIconLayoutSidebar extends BvComponent {}

export declare class BIconLayoutSidebarInset extends BvComponent {}

export declare class BIconLayoutSidebarInsetReverse extends BvComponent {}

export declare class BIconLayoutSidebarReverse extends BvComponent {}

export declare class BIconLayoutSplit extends BvComponent {}

export declare class BIconLayoutTextSidebar extends BvComponent {}

export declare class BIconLayoutTextSidebarReverse extends BvComponent {}

export declare class BIconLayoutTextWindow extends BvComponent {}

export declare class BIconLayoutTextWindowReverse extends BvComponent {}

export declare class BIconLayoutThreeColumns extends BvComponent {}

export declare class BIconLayoutWtf extends BvComponent {}

export declare class BIconLifePreserver extends BvComponent {}

export declare class BIconLightning extends BvComponent {}

export declare class BIconLightningFill extends BvComponent {}

export declare class BIconLink extends BvComponent {}

export declare class BIconLink45deg extends BvComponent {}

export declare class BIconLinkedin extends BvComponent {}

export declare class BIconList extends BvComponent {}

export declare class BIconListCheck extends BvComponent {}

export declare class BIconListNested extends BvComponent {}

export declare class BIconListOl extends BvComponent {}

export declare class BIconListStars extends BvComponent {}

export declare class BIconListTask extends BvComponent {}

export declare class BIconListUl extends BvComponent {}

export declare class BIconLock extends BvComponent {}

export declare class BIconLockFill extends BvComponent {}

export declare class BIconMailbox extends BvComponent {}

export declare class BIconMailbox2 extends BvComponent {}

export declare class BIconMap extends BvComponent {}

export declare class BIconMapFill extends BvComponent {}

export declare class BIconMarkdown extends BvComponent {}

export declare class BIconMarkdownFill extends BvComponent {}

export declare class BIconMenuApp extends BvComponent {}

export declare class BIconMenuAppFill extends BvComponent {}

export declare class BIconMenuButton extends BvComponent {}

export declare class BIconMenuButtonFill extends BvComponent {}

export declare class BIconMenuButtonWide extends BvComponent {}

export declare class BIconMenuButtonWideFill extends BvComponent {}

export declare class BIconMenuDown extends BvComponent {}

export declare class BIconMenuUp extends BvComponent {}

export declare class BIconMic extends BvComponent {}

export declare class BIconMicFill extends BvComponent {}

export declare class BIconMicMute extends BvComponent {}

export declare class BIconMicMuteFill extends BvComponent {}

export declare class BIconMinecart extends BvComponent {}

export declare class BIconMinecartLoaded extends BvComponent {}

export declare class BIconMoon extends BvComponent {}

export declare class BIconMouse extends BvComponent {}

export declare class BIconMouse2 extends BvComponent {}

export declare class BIconMouse3 extends BvComponent {}

export declare class BIconMusicNote extends BvComponent {}

export declare class BIconMusicNoteBeamed extends BvComponent {}

export declare class BIconMusicNoteList extends BvComponent {}

export declare class BIconMusicPlayer extends BvComponent {}

export declare class BIconMusicPlayerFill extends BvComponent {}

export declare class BIconNewspaper extends BvComponent {}

export declare class BIconNodeMinus extends BvComponent {}

export declare class BIconNodeMinusFill extends BvComponent {}

export declare class BIconNodePlus extends BvComponent {}

export declare class BIconNodePlusFill extends BvComponent {}

export declare class BIconNut extends BvComponent {}

export declare class BIconNutFill extends BvComponent {}

export declare class BIconOctagon extends BvComponent {}

export declare class BIconOctagonFill extends BvComponent {}

export declare class BIconOctagonHalf extends BvComponent {}

export declare class BIconOption extends BvComponent {}

export declare class BIconOutlet extends BvComponent {}

export declare class BIconPaperclip extends BvComponent {}

export declare class BIconParagraph extends BvComponent {}

export declare class BIconPatchCheck extends BvComponent {}

export declare class BIconPatchCheckFll extends BvComponent {}

export declare class BIconPatchExclamation extends BvComponent {}

export declare class BIconPatchExclamationFll extends BvComponent {}

export declare class BIconPatchMinus extends BvComponent {}

export declare class BIconPatchMinusFll extends BvComponent {}

export declare class BIconPatchPlus extends BvComponent {}

export declare class BIconPatchPlusFll extends BvComponent {}

export declare class BIconPatchQuestion extends BvComponent {}

export declare class BIconPatchQuestionFll extends BvComponent {}

export declare class BIconPause extends BvComponent {}

export declare class BIconPauseBtn extends BvComponent {}

export declare class BIconPauseBtnFill extends BvComponent {}

export declare class BIconPauseCircle extends BvComponent {}

export declare class BIconPauseCircleFill extends BvComponent {}

export declare class BIconPauseFill extends BvComponent {}

export declare class BIconPeace extends BvComponent {}

export declare class BIconPeaceFill extends BvComponent {}

export declare class BIconPen extends BvComponent {}

export declare class BIconPenFill extends BvComponent {}

export declare class BIconPencil extends BvComponent {}

export declare class BIconPencilFill extends BvComponent {}

export declare class BIconPencilSquare extends BvComponent {}

export declare class BIconPentagon extends BvComponent {}

export declare class BIconPentagonFill extends BvComponent {}

export declare class BIconPentagonHalf extends BvComponent {}

export declare class BIconPeople extends BvComponent {}

export declare class BIconPeopleFill extends BvComponent {}

export declare class BIconPercent extends BvComponent {}

export declare class BIconPerson extends BvComponent {}

export declare class BIconPersonBadge extends BvComponent {}

export declare class BIconPersonBadgeFill extends BvComponent {}

export declare class BIconPersonBoundingBox extends BvComponent {}

export declare class BIconPersonCheck extends BvComponent {}

export declare class BIconPersonCheckFill extends BvComponent {}

export declare class BIconPersonCircle extends BvComponent {}

export declare class BIconPersonDash extends BvComponent {}

export declare class BIconPersonDashFill extends BvComponent {}

export declare class BIconPersonFill extends BvComponent {}

export declare class BIconPersonLinesFill extends BvComponent {}

export declare class BIconPersonPlus extends BvComponent {}

export declare class BIconPersonPlusFill extends BvComponent {}

export declare class BIconPersonSquare extends BvComponent {}

export declare class BIconPersonX extends BvComponent {}

export declare class BIconPersonXFill extends BvComponent {}

export declare class BIconPhone extends BvComponent {}

export declare class BIconPhoneFill extends BvComponent {}

export declare class BIconPhoneLandscape extends BvComponent {}

export declare class BIconPhoneLandscapeFill extends BvComponent {}

export declare class BIconPhoneVibrate extends BvComponent {}

export declare class BIconPieChart extends BvComponent {}

export declare class BIconPieChartFill extends BvComponent {}

export declare class BIconPip extends BvComponent {}

export declare class BIconPipFill extends BvComponent {}

export declare class BIconPlay extends BvComponent {}

export declare class BIconPlayBtn extends BvComponent {}

export declare class BIconPlayBtnFill extends BvComponent {}

export declare class BIconPlayCircle extends BvComponent {}

export declare class BIconPlayCircleFill extends BvComponent {}

export declare class BIconPlayFill extends BvComponent {}

export declare class BIconPlug extends BvComponent {}

export declare class BIconPlugFill extends BvComponent {}

export declare class BIconPlus extends BvComponent {}

export declare class BIconPlusCircle extends BvComponent {}

export declare class BIconPlusCircleFill extends BvComponent {}

export declare class BIconPlusSquare extends BvComponent {}

export declare class BIconPlusSquareFill extends BvComponent {}

export declare class BIconPower extends BvComponent {}

export declare class BIconPrinter extends BvComponent {}

export declare class BIconPrinterFill extends BvComponent {}

export declare class BIconPuzzle extends BvComponent {}

export declare class BIconPuzzleFill extends BvComponent {}

export declare class BIconQuestion extends BvComponent {}

export declare class BIconQuestionCircle extends BvComponent {}

export declare class BIconQuestionCircleFill extends BvComponent {}

export declare class BIconQuestionDiamond extends BvComponent {}

export declare class BIconQuestionDiamondFill extends BvComponent {}

export declare class BIconQuestionOctagon extends BvComponent {}

export declare class BIconQuestionOctagonFill extends BvComponent {}

export declare class BIconQuestionSquare extends BvComponent {}

export declare class BIconQuestionSquareFill extends BvComponent {}

export declare class BIconReceipt extends BvComponent {}

export declare class BIconReceiptCutoff extends BvComponent {}

export declare class BIconReception0 extends BvComponent {}

export declare class BIconReception1 extends BvComponent {}

export declare class BIconReception2 extends BvComponent {}

export declare class BIconReception3 extends BvComponent {}

export declare class BIconReception4 extends BvComponent {}

export declare class BIconRecord extends BvComponent {}

export declare class BIconRecord2 extends BvComponent {}

export declare class BIconRecord2Fill extends BvComponent {}

export declare class BIconRecordBtn extends BvComponent {}

export declare class BIconRecordBtnFill extends BvComponent {}

export declare class BIconRecordCircle extends BvComponent {}

export declare class BIconRecordCircleFill extends BvComponent {}

export declare class BIconRecordFill extends BvComponent {}

export declare class BIconReply extends BvComponent {}

export declare class BIconReplyAll extends BvComponent {}

export declare class BIconReplyAllFill extends BvComponent {}

export declare class BIconReplyFill extends BvComponent {}

export declare class BIconRss extends BvComponent {}

export declare class BIconRssFill extends BvComponent {}

export declare class BIconScissors extends BvComponent {}

export declare class BIconScrewdriver extends BvComponent {}

export declare class BIconSearch extends BvComponent {}

export declare class BIconSegmentedNav extends BvComponent {}

export declare class BIconServer extends BvComponent {}

export declare class BIconShare extends BvComponent {}

export declare class BIconShareFill extends BvComponent {}

export declare class BIconShield extends BvComponent {}

export declare class BIconShieldCheck extends BvComponent {}

export declare class BIconShieldExclamation extends BvComponent {}

export declare class BIconShieldFill extends BvComponent {}

export declare class BIconShieldFillCheck extends BvComponent {}

export declare class BIconShieldFillExclamation extends BvComponent {}

export declare class BIconShieldFillMinus extends BvComponent {}

export declare class BIconShieldFillPlus extends BvComponent {}

export declare class BIconShieldFillX extends BvComponent {}

export declare class BIconShieldLock extends BvComponent {}

export declare class BIconShieldLockFill extends BvComponent {}

export declare class BIconShieldMinus extends BvComponent {}

export declare class BIconShieldPlus extends BvComponent {}

export declare class BIconShieldShaded extends BvComponent {}

export declare class BIconShieldSlash extends BvComponent {}

export declare class BIconShieldSlashFill extends BvComponent {}

export declare class BIconShieldX extends BvComponent {}

export declare class BIconShift extends BvComponent {}

export declare class BIconShiftFill extends BvComponent {}

export declare class BIconShop extends BvComponent {}

export declare class BIconShopWindow extends BvComponent {}

export declare class BIconShuffle extends BvComponent {}

export declare class BIconSignpost extends BvComponent {}

export declare class BIconSignpost2 extends BvComponent {}

export declare class BIconSignpost2Fill extends BvComponent {}

export declare class BIconSignpostFill extends BvComponent {}

export declare class BIconSignpostSplit extends BvComponent {}

export declare class BIconSignpostSplitFill extends BvComponent {}

export declare class BIconSim extends BvComponent {}

export declare class BIconSimFill extends BvComponent {}

export declare class BIconSkipBackward extends BvComponent {}

export declare class BIconSkipBackwardBtn extends BvComponent {}

export declare class BIconSkipBackwardBtnFill extends BvComponent {}

export declare class BIconSkipBackwardCircle extends BvComponent {}

export declare class BIconSkipBackwardCircleFill extends BvComponent {}

export declare class BIconSkipBackwardFill extends BvComponent {}

export declare class BIconSkipEnd extends BvComponent {}

export declare class BIconSkipEndBtn extends BvComponent {}

export declare class BIconSkipEndBtnFill extends BvComponent {}

export declare class BIconSkipEndCircle extends BvComponent {}

export declare class BIconSkipEndCircleFill extends BvComponent {}

export declare class BIconSkipEndFill extends BvComponent {}

export declare class BIconSkipForward extends BvComponent {}

export declare class BIconSkipForwardBtn extends BvComponent {}

export declare class BIconSkipForwardBtnFill extends BvComponent {}

export declare class BIconSkipForwardCircle extends BvComponent {}

export declare class BIconSkipForwardCircleFill extends BvComponent {}

export declare class BIconSkipForwardFill extends BvComponent {}

export declare class BIconSkipStart extends BvComponent {}

export declare class BIconSkipStartBtn extends BvComponent {}

export declare class BIconSkipStartBtnFill extends BvComponent {}

export declare class BIconSkipStartCircle extends BvComponent {}

export declare class BIconSkipStartCircleFill extends BvComponent {}

export declare class BIconSkipStartFill extends BvComponent {}

export declare class BIconSlack extends BvComponent {}

export declare class BIconSlash extends BvComponent {}

export declare class BIconSlashCircle extends BvComponent {}

export declare class BIconSlashCircleFill extends BvComponent {}

export declare class BIconSlashSquare extends BvComponent {}

export declare class BIconSlashSquareFill extends BvComponent {}

export declare class BIconSliders extends BvComponent {}

export declare class BIconSmartwatch extends BvComponent {}

export declare class BIconSortAlphaDown extends BvComponent {}

export declare class BIconSortAlphaDownAlt extends BvComponent {}

export declare class BIconSortAlphaUp extends BvComponent {}

export declare class BIconSortAlphaUpAlt extends BvComponent {}

export declare class BIconSortDown extends BvComponent {}

export declare class BIconSortDownAlt extends BvComponent {}

export declare class BIconSortNumericDown extends BvComponent {}

export declare class BIconSortNumericDownAlt extends BvComponent {}

export declare class BIconSortNumericUp extends BvComponent {}

export declare class BIconSortNumericUpAlt extends BvComponent {}

export declare class BIconSortUp extends BvComponent {}

export declare class BIconSortUpAlt extends BvComponent {}

export declare class BIconSoundwave extends BvComponent {}

export declare class BIconSpeaker extends BvComponent {}

export declare class BIconSpeakerFill extends BvComponent {}

export declare class BIconSpellcheck extends BvComponent {}

export declare class BIconSquare extends BvComponent {}

export declare class BIconSquareFill extends BvComponent {}

export declare class BIconSquareHalf extends BvComponent {}

export declare class BIconStar extends BvComponent {}

export declare class BIconStarFill extends BvComponent {}

export declare class BIconStarHalf extends BvComponent {}

export declare class BIconStickies extends BvComponent {}

export declare class BIconStickiesFill extends BvComponent {}

export declare class BIconSticky extends BvComponent {}

export declare class BIconStickyFill extends BvComponent {}

export declare class BIconStop extends BvComponent {}

export declare class BIconStopBtn extends BvComponent {}

export declare class BIconStopBtnFill extends BvComponent {}

export declare class BIconStopCircle extends BvComponent {}

export declare class BIconStopCircleFill extends BvComponent {}

export declare class BIconStopFill extends BvComponent {}

export declare class BIconStoplights extends BvComponent {}

export declare class BIconStoplightsFill extends BvComponent {}

export declare class BIconStopwatch extends BvComponent {}

export declare class BIconStopwatchFill extends BvComponent {}

export declare class BIconSubtract extends BvComponent {}

export declare class BIconSuitClub extends BvComponent {}

export declare class BIconSuitClubFill extends BvComponent {}

export declare class BIconSuitDiamond extends BvComponent {}

export declare class BIconSuitDiamondFill extends BvComponent {}

export declare class BIconSuitHeart extends BvComponent {}

export declare class BIconSuitHeartFill extends BvComponent {}

export declare class BIconSuitSpade extends BvComponent {}

export declare class BIconSuitSpadeFill extends BvComponent {}

export declare class BIconSun extends BvComponent {}

export declare class BIconSunglasses extends BvComponent {}

export declare class BIconTable extends BvComponent {}

export declare class BIconTablet extends BvComponent {}

export declare class BIconTabletFill extends BvComponent {}

export declare class BIconTabletLandscape extends BvComponent {}

export declare class BIconTabletLandscapeFill extends BvComponent {}

export declare class BIconTag extends BvComponent {}

export declare class BIconTagFill extends BvComponent {}

export declare class BIconTags extends BvComponent {}

export declare class BIconTagsFill extends BvComponent {}

export declare class BIconTelephone extends BvComponent {}

export declare class BIconTelephoneFill extends BvComponent {}

export declare class BIconTelephoneForward extends BvComponent {}

export declare class BIconTelephoneForwardFill extends BvComponent {}

export declare class BIconTelephoneInbound extends BvComponent {}

export declare class BIconTelephoneInboundFill extends BvComponent {}

export declare class BIconTelephoneMinus extends BvComponent {}

export declare class BIconTelephoneMinusFill extends BvComponent {}

export declare class BIconTelephoneOutbound extends BvComponent {}

export declare class BIconTelephoneOutboundFill extends BvComponent {}

export declare class BIconTelephonePlus extends BvComponent {}

export declare class BIconTelephonePlusFill extends BvComponent {}

export declare class BIconTelephoneX extends BvComponent {}

export declare class BIconTelephoneXFill extends BvComponent {}

export declare class BIconTerminal extends BvComponent {}

export declare class BIconTerminalFill extends BvComponent {}

export declare class BIconTextCenter extends BvComponent {}

export declare class BIconTextIndentLeft extends BvComponent {}

export declare class BIconTextIndentRight extends BvComponent {}

export declare class BIconTextLeft extends BvComponent {}

export declare class BIconTextParagraph extends BvComponent {}

export declare class BIconTextRight extends BvComponent {}

export declare class BIconTextarea extends BvComponent {}

export declare class BIconTextareaResize extends BvComponent {}

export declare class BIconTextareaT extends BvComponent {}

export declare class BIconThermometer extends BvComponent {}

export declare class BIconThermometerHalf extends BvComponent {}

export declare class BIconThreeDots extends BvComponent {}

export declare class BIconThreeDotsVertical extends BvComponent {}

export declare class BIconToggle2Off extends BvComponent {}

export declare class BIconToggle2On extends BvComponent {}

export declare class BIconToggleOff extends BvComponent {}

export declare class BIconToggleOn extends BvComponent {}

export declare class BIconToggles extends BvComponent {}

export declare class BIconToggles2 extends BvComponent {}

export declare class BIconTools extends BvComponent {}

export declare class BIconTrash extends BvComponent {}

export declare class BIconTrash2 extends BvComponent {}

export declare class BIconTrash2Fill extends BvComponent {}

export declare class BIconTrashFill extends BvComponent {}

export declare class BIconTree extends BvComponent {}

export declare class BIconTreeFill extends BvComponent {}

export declare class BIconTriangle extends BvComponent {}

export declare class BIconTriangleFill extends BvComponent {}

export declare class BIconTriangleHalf extends BvComponent {}

export declare class BIconTrophy extends BvComponent {}

export declare class BIconTrophyFill extends BvComponent {}

export declare class BIconTruck extends BvComponent {}

export declare class BIconTruckFlatbed extends BvComponent {}

export declare class BIconTv extends BvComponent {}

export declare class BIconTvFill extends BvComponent {}

export declare class BIconTwitch extends BvComponent {}

export declare class BIconTwitter extends BvComponent {}

export declare class BIconType extends BvComponent {}

export declare class BIconTypeBold extends BvComponent {}

export declare class BIconTypeH1 extends BvComponent {}

export declare class BIconTypeH2 extends BvComponent {}

export declare class BIconTypeH3 extends BvComponent {}

export declare class BIconTypeItalic extends BvComponent {}

export declare class BIconTypeStrikethrough extends BvComponent {}

export declare class BIconTypeUnderline extends BvComponent {}

export declare class BIconUiChecks extends BvComponent {}

export declare class BIconUiChecksGrid extends BvComponent {}

export declare class BIconUiRadios extends BvComponent {}

export declare class BIconUiRadiosGrid extends BvComponent {}

export declare class BIconUnion extends BvComponent {}

export declare class BIconUnlock extends BvComponent {}

export declare class BIconUnlockFill extends BvComponent {}

export declare class BIconUpc extends BvComponent {}

export declare class BIconUpcScan extends BvComponent {}

export declare class BIconUpload extends BvComponent {}

export declare class BIconVectorPen extends BvComponent {}

export declare class BIconViewList extends BvComponent {}

export declare class BIconViewStacked extends BvComponent {}

export declare class BIconVinyl extends BvComponent {}

export declare class BIconVinylFill extends BvComponent {}

export declare class BIconVoicemail extends BvComponent {}

export declare class BIconVolumeDown extends BvComponent {}

export declare class BIconVolumeDownFill extends BvComponent {}

export declare class BIconVolumeMute extends BvComponent {}

export declare class BIconVolumeMuteFill extends BvComponent {}

export declare class BIconVolumeOff extends BvComponent {}

export declare class BIconVolumeOffFill extends BvComponent {}

export declare class BIconVolumeUp extends BvComponent {}

export declare class BIconVolumeUpFill extends BvComponent {}

export declare class BIconVr extends BvComponent {}

export declare class BIconWallet extends BvComponent {}

export declare class BIconWallet2 extends BvComponent {}

export declare class BIconWalletFill extends BvComponent {}

export declare class BIconWatch extends BvComponent {}

export declare class BIconWifi extends BvComponent {}

export declare class BIconWifi1 extends BvComponent {}

export declare class BIconWifi2 extends BvComponent {}

export declare class BIconWifiOff extends BvComponent {}

export declare class BIconWindow extends BvComponent {}

export declare class BIconWrench extends BvComponent {}

export declare class BIconX extends BvComponent {}

export declare class BIconXCircle extends BvComponent {}

export declare class BIconXCircleFill extends BvComponent {}

export declare class BIconXDiamond extends BvComponent {}

export declare class BIconXDiamondFill extends BvComponent {}

export declare class BIconXOctagon extends BvComponent {}

export declare class BIconXOctagonFill extends BvComponent {}

export declare class BIconXSquare extends BvComponent {}

export declare class BIconXSquareFill extends BvComponent {}

export declare class BIconYoutube extends BvComponent {}

export declare class BIconZoomIn extends BvComponent {}

export declare class BIconZoomOut extends BvComponent {}

// --- END AUTO-GENERATED FILE ---
