// --- BEGIN AUTO-GENERATED FILE ---
//
// @IconsVersion: 1.0.0-alpha2
// @Generated: 2020-01-22T07:06:51.693Z
//
// This file is generated on each build. Do not edit this file!

import Vue from 'vue'
import { BvComponent } from '../'

// --- BootstrapVue custom icons ---

export declare class BIconBlank extends BvComponent {}

// --- Bootstrap Icons ---

export declare class BIconAlarm extends BvComponent {}

export declare class BIconAlarmFill extends BvComponent {}

export declare class BIconAlertCircle extends BvComponent {}

export declare class BIconAlertCircleFill extends BvComponent {}

export declare class BIconAlertOctagon extends BvComponent {}

export declare class BIconAlertOctagonFill extends BvComponent {}

export declare class BIconAlertSquare extends BvComponent {}

export declare class BIconAlertSquareFill extends BvComponent {}

export declare class BIconAlertTriangle extends BvComponent {}

export declare class BIconAlertTriangleFill extends BvComponent {}

export declare class BIconArchive extends BvComponent {}

export declare class BIconArchiveFill extends BvComponent {}

export declare class BIconArrowBarBottom extends BvComponent {}

export declare class BIconArrowBarLeft extends BvComponent {}

export declare class BIconArrowBarRight extends BvComponent {}

export declare class BIconArrowBarUp extends BvComponent {}

export declare class BIconArrowClockwise extends BvComponent {}

export declare class BIconArrowCounterclockwise extends BvComponent {}

export declare class BIconArrowDown extends BvComponent {}

export declare class BIconArrowDownLeft extends BvComponent {}

export declare class BIconArrowDownRight extends BvComponent {}

export declare class BIconArrowDownShort extends BvComponent {}

export declare class BIconArrowLeft extends BvComponent {}

export declare class BIconArrowLeftRight extends BvComponent {}

export declare class BIconArrowLeftShort extends BvComponent {}

export declare class BIconArrowRepeat extends BvComponent {}

export declare class BIconArrowRight extends BvComponent {}

export declare class BIconArrowRightShort extends BvComponent {}

export declare class BIconArrowUp extends BvComponent {}

export declare class BIconArrowUpDown extends BvComponent {}

export declare class BIconArrowUpLeft extends BvComponent {}

export declare class BIconArrowUpRight extends BvComponent {}

export declare class BIconArrowUpShort extends BvComponent {}

export declare class BIconArrowsAngleContract extends BvComponent {}

export declare class BIconArrowsAngleExpand extends BvComponent {}

export declare class BIconArrowsCollapse extends BvComponent {}

export declare class BIconArrowsExpand extends BvComponent {}

export declare class BIconArrowsFullscreen extends BvComponent {}

export declare class BIconAt extends BvComponent {}

export declare class BIconAward extends BvComponent {}

export declare class BIconBackspace extends BvComponent {}

export declare class BIconBackspaceFill extends BvComponent {}

export declare class BIconBackspaceReverse extends BvComponent {}

export declare class BIconBackspaceReverseFill extends BvComponent {}

export declare class BIconBarChart extends BvComponent {}

export declare class BIconBarChartFill extends BvComponent {}

export declare class BIconBattery extends BvComponent {}

export declare class BIconBatteryCharging extends BvComponent {}

export declare class BIconBatteryFull extends BvComponent {}

export declare class BIconBell extends BvComponent {}

export declare class BIconBellFill extends BvComponent {}

export declare class BIconBlockquoteLeft extends BvComponent {}

export declare class BIconBlockquoteRight extends BvComponent {}

export declare class BIconBook extends BvComponent {}

export declare class BIconBookHalfFill extends BvComponent {}

export declare class BIconBookmark extends BvComponent {}

export declare class BIconBookmarkFill extends BvComponent {}

export declare class BIconBootstrap extends BvComponent {}

export declare class BIconBootstrapFill extends BvComponent {}

export declare class BIconBootstrapReboot extends BvComponent {}

export declare class BIconBoxArrowBottomLeft extends BvComponent {}

export declare class BIconBoxArrowBottomRight extends BvComponent {}

export declare class BIconBoxArrowDown extends BvComponent {}

export declare class BIconBoxArrowLeft extends BvComponent {}

export declare class BIconBoxArrowRight extends BvComponent {}

export declare class BIconBoxArrowUp extends BvComponent {}

export declare class BIconBoxArrowUpLeft extends BvComponent {}

export declare class BIconBoxArrowUpRight extends BvComponent {}

export declare class BIconBraces extends BvComponent {}

export declare class BIconBrightnessFillHigh extends BvComponent {}

export declare class BIconBrightnessFillLow extends BvComponent {}

export declare class BIconBrightnessHigh extends BvComponent {}

export declare class BIconBrightnessLow extends BvComponent {}

export declare class BIconBrush extends BvComponent {}

export declare class BIconBucket extends BvComponent {}

export declare class BIconBucketFill extends BvComponent {}

export declare class BIconBuilding extends BvComponent {}

export declare class BIconBullseye extends BvComponent {}

export declare class BIconCalendar extends BvComponent {}

export declare class BIconCalendarFill extends BvComponent {}

export declare class BIconCamera extends BvComponent {}

export declare class BIconCameraVideo extends BvComponent {}

export declare class BIconCameraVideoFill extends BvComponent {}

export declare class BIconCapslock extends BvComponent {}

export declare class BIconCapslockFill extends BvComponent {}

export declare class BIconChat extends BvComponent {}

export declare class BIconChatFill extends BvComponent {}

export declare class BIconCheck extends BvComponent {}

export declare class BIconCheckBox extends BvComponent {}

export declare class BIconCheckCircle extends BvComponent {}

export declare class BIconChevronCompactDown extends BvComponent {}

export declare class BIconChevronCompactLeft extends BvComponent {}

export declare class BIconChevronCompactRight extends BvComponent {}

export declare class BIconChevronCompactUp extends BvComponent {}

export declare class BIconChevronDown extends BvComponent {}

export declare class BIconChevronLeft extends BvComponent {}

export declare class BIconChevronRight extends BvComponent {}

export declare class BIconChevronUp extends BvComponent {}

export declare class BIconCircle extends BvComponent {}

export declare class BIconCircleFill extends BvComponent {}

export declare class BIconCircleHalf extends BvComponent {}

export declare class BIconCircleSlash extends BvComponent {}

export declare class BIconClock extends BvComponent {}

export declare class BIconClockFill extends BvComponent {}

export declare class BIconCloud extends BvComponent {}

export declare class BIconCloudDownload extends BvComponent {}

export declare class BIconCloudFill extends BvComponent {}

export declare class BIconCloudUpload extends BvComponent {}

export declare class BIconCode extends BvComponent {}

export declare class BIconCodeSlash extends BvComponent {}

export declare class BIconColumns extends BvComponent {}

export declare class BIconColumnsGutters extends BvComponent {}

export declare class BIconCommand extends BvComponent {}

export declare class BIconCompass extends BvComponent {}

export declare class BIconCone extends BvComponent {}

export declare class BIconConeStriped extends BvComponent {}

export declare class BIconController extends BvComponent {}

export declare class BIconCreditCard extends BvComponent {}

export declare class BIconCursor extends BvComponent {}

export declare class BIconCursorFill extends BvComponent {}

export declare class BIconDash extends BvComponent {}

export declare class BIconDiamond extends BvComponent {}

export declare class BIconDiamondHalf extends BvComponent {}

export declare class BIconDisplay extends BvComponent {}

export declare class BIconDisplayFill extends BvComponent {}

export declare class BIconDocument extends BvComponent {}

export declare class BIconDocumentCode extends BvComponent {}

export declare class BIconDocumentDiff extends BvComponent {}

export declare class BIconDocumentRichtext extends BvComponent {}

export declare class BIconDocumentSpreadsheet extends BvComponent {}

export declare class BIconDocumentText extends BvComponent {}

export declare class BIconDocuments extends BvComponent {}

export declare class BIconDocumentsAlt extends BvComponent {}

export declare class BIconDot extends BvComponent {}

export declare class BIconDownload extends BvComponent {}

export declare class BIconEggFried extends BvComponent {}

export declare class BIconEject extends BvComponent {}

export declare class BIconEjectFill extends BvComponent {}

export declare class BIconEnvelope extends BvComponent {}

export declare class BIconEnvelopeFill extends BvComponent {}

export declare class BIconEnvelopeOpen extends BvComponent {}

export declare class BIconEnvelopeOpenFill extends BvComponent {}

export declare class BIconEye extends BvComponent {}

export declare class BIconEyeFill extends BvComponent {}

export declare class BIconEyeSlash extends BvComponent {}

export declare class BIconEyeSlashFill extends BvComponent {}

export declare class BIconFilter extends BvComponent {}

export declare class BIconFlag extends BvComponent {}

export declare class BIconFlagFill extends BvComponent {}

export declare class BIconFolder extends BvComponent {}

export declare class BIconFolderFill extends BvComponent {}

export declare class BIconFolderSymlink extends BvComponent {}

export declare class BIconFolderSymlinkFill extends BvComponent {}

export declare class BIconFonts extends BvComponent {}

export declare class BIconForward extends BvComponent {}

export declare class BIconForwardFill extends BvComponent {}

export declare class BIconGear extends BvComponent {}

export declare class BIconGearFill extends BvComponent {}

export declare class BIconGearWide extends BvComponent {}

export declare class BIconGearWideConnected extends BvComponent {}

export declare class BIconGeo extends BvComponent {}

export declare class BIconGraphDown extends BvComponent {}

export declare class BIconGraphUp extends BvComponent {}

export declare class BIconGrid extends BvComponent {}

export declare class BIconGridFill extends BvComponent {}

export declare class BIconHammer extends BvComponent {}

export declare class BIconHash extends BvComponent {}

export declare class BIconHeart extends BvComponent {}

export declare class BIconHeartFill extends BvComponent {}

export declare class BIconHouse extends BvComponent {}

export declare class BIconHouseFill extends BvComponent {}

export declare class BIconImage extends BvComponent {}

export declare class BIconImageAlt extends BvComponent {}

export declare class BIconImageFill extends BvComponent {}

export declare class BIconImages extends BvComponent {}

export declare class BIconInbox extends BvComponent {}

export declare class BIconInboxFill extends BvComponent {}

export declare class BIconInboxes extends BvComponent {}

export declare class BIconInboxesFill extends BvComponent {}

export declare class BIconInfo extends BvComponent {}

export declare class BIconInfoFill extends BvComponent {}

export declare class BIconInfoSquare extends BvComponent {}

export declare class BIconInfoSquareFill extends BvComponent {}

export declare class BIconJustify extends BvComponent {}

export declare class BIconJustifyLeft extends BvComponent {}

export declare class BIconJustifyRight extends BvComponent {}

export declare class BIconKanban extends BvComponent {}

export declare class BIconKanbanFill extends BvComponent {}

export declare class BIconLaptop extends BvComponent {}

export declare class BIconLayoutSidebar extends BvComponent {}

export declare class BIconLayoutSidebarReverse extends BvComponent {}

export declare class BIconLayoutSplit extends BvComponent {}

export declare class BIconList extends BvComponent {}

export declare class BIconListCheck extends BvComponent {}

export declare class BIconListOl extends BvComponent {}

export declare class BIconListTask extends BvComponent {}

export declare class BIconListUl extends BvComponent {}

export declare class BIconLock extends BvComponent {}

export declare class BIconLockFill extends BvComponent {}

export declare class BIconMap extends BvComponent {}

export declare class BIconMic extends BvComponent {}

export declare class BIconMoon extends BvComponent {}

export declare class BIconMusicPlayer extends BvComponent {}

export declare class BIconMusicPlayerFill extends BvComponent {}

export declare class BIconOption extends BvComponent {}

export declare class BIconOutlet extends BvComponent {}

export declare class BIconPause extends BvComponent {}

export declare class BIconPauseFill extends BvComponent {}

export declare class BIconPen extends BvComponent {}

export declare class BIconPencil extends BvComponent {}

export declare class BIconPeople extends BvComponent {}

export declare class BIconPeopleFill extends BvComponent {}

export declare class BIconPerson extends BvComponent {}

export declare class BIconPersonFill extends BvComponent {}

export declare class BIconPhone extends BvComponent {}

export declare class BIconPhoneLandscape extends BvComponent {}

export declare class BIconPieChart extends BvComponent {}

export declare class BIconPieChartFill extends BvComponent {}

export declare class BIconPlay extends BvComponent {}

export declare class BIconPlayFill extends BvComponent {}

export declare class BIconPlug extends BvComponent {}

export declare class BIconPlus extends BvComponent {}

export declare class BIconPower extends BvComponent {}

export declare class BIconQuestion extends BvComponent {}

export declare class BIconQuestionFill extends BvComponent {}

export declare class BIconQuestionSquare extends BvComponent {}

export declare class BIconQuestionSquareFill extends BvComponent {}

export declare class BIconReply extends BvComponent {}

export declare class BIconReplyAll extends BvComponent {}

export declare class BIconReplyAllFill extends BvComponent {}

export declare class BIconReplyFill extends BvComponent {}

export declare class BIconScrewdriver extends BvComponent {}

export declare class BIconSearch extends BvComponent {}

export declare class BIconShield extends BvComponent {}

export declare class BIconShieldFill extends BvComponent {}

export declare class BIconShieldLock extends BvComponent {}

export declare class BIconShieldLockFill extends BvComponent {}

export declare class BIconShieldShaded extends BvComponent {}

export declare class BIconShift extends BvComponent {}

export declare class BIconShiftFill extends BvComponent {}

export declare class BIconSkipBackward extends BvComponent {}

export declare class BIconSkipBackwardFill extends BvComponent {}

export declare class BIconSkipEnd extends BvComponent {}

export declare class BIconSkipEndFill extends BvComponent {}

export declare class BIconSkipForward extends BvComponent {}

export declare class BIconSkipForwardFill extends BvComponent {}

export declare class BIconSkipStart extends BvComponent {}

export declare class BIconSkipStartFill extends BvComponent {}

export declare class BIconSpeaker extends BvComponent {}

export declare class BIconSquare extends BvComponent {}

export declare class BIconSquareFill extends BvComponent {}

export declare class BIconSquareHalf extends BvComponent {}

export declare class BIconStar extends BvComponent {}

export declare class BIconStarFill extends BvComponent {}

export declare class BIconStarHalf extends BvComponent {}

export declare class BIconStop extends BvComponent {}

export declare class BIconStopFill extends BvComponent {}

export declare class BIconStopwatch extends BvComponent {}

export declare class BIconStopwatchFill extends BvComponent {}

export declare class BIconSun extends BvComponent {}

export declare class BIconTable extends BvComponent {}

export declare class BIconTablet extends BvComponent {}

export declare class BIconTabletLandscape extends BvComponent {}

export declare class BIconTag extends BvComponent {}

export declare class BIconTagFill extends BvComponent {}

export declare class BIconTerminal extends BvComponent {}

export declare class BIconTerminalFill extends BvComponent {}

export declare class BIconTextCenter extends BvComponent {}

export declare class BIconTextIndentLeft extends BvComponent {}

export declare class BIconTextIndentRight extends BvComponent {}

export declare class BIconTextLeft extends BvComponent {}

export declare class BIconTextRight extends BvComponent {}

export declare class BIconThreeDots extends BvComponent {}

export declare class BIconThreeDotsVertical extends BvComponent {}

export declare class BIconToggleOff extends BvComponent {}

export declare class BIconToggleOn extends BvComponent {}

export declare class BIconToggles extends BvComponent {}

export declare class BIconTools extends BvComponent {}

export declare class BIconTrash extends BvComponent {}

export declare class BIconTrashFill extends BvComponent {}

export declare class BIconTriangle extends BvComponent {}

export declare class BIconTriangleFill extends BvComponent {}

export declare class BIconTriangleHalf extends BvComponent {}

export declare class BIconTrophy extends BvComponent {}

export declare class BIconTv extends BvComponent {}

export declare class BIconTvFill extends BvComponent {}

export declare class BIconType extends BvComponent {}

export declare class BIconTypeBold extends BvComponent {}

export declare class BIconTypeH1 extends BvComponent {}

export declare class BIconTypeH2 extends BvComponent {}

export declare class BIconTypeH3 extends BvComponent {}

export declare class BIconTypeItalic extends BvComponent {}

export declare class BIconTypeStrikethrough extends BvComponent {}

export declare class BIconTypeUnderline extends BvComponent {}

export declare class BIconUnlock extends BvComponent {}

export declare class BIconUnlockFill extends BvComponent {}

export declare class BIconUpload extends BvComponent {}

export declare class BIconVolumeDown extends BvComponent {}

export declare class BIconVolumeDownFill extends BvComponent {}

export declare class BIconVolumeMute extends BvComponent {}

export declare class BIconVolumeMuteFill extends BvComponent {}

export declare class BIconVolumeUp extends BvComponent {}

export declare class BIconVolumeUpFill extends BvComponent {}

export declare class BIconWallet extends BvComponent {}

export declare class BIconWatch extends BvComponent {}

export declare class BIconWifi extends BvComponent {}

export declare class BIconWindow extends BvComponent {}

export declare class BIconWrench extends BvComponent {}

export declare class BIconX extends BvComponent {}

export declare class BIconXCircle extends BvComponent {}

export declare class BIconXCircleFill extends BvComponent {}

export declare class BIconXOctagon extends BvComponent {}

export declare class BIconXOctagonFill extends BvComponent {}

export declare class BIconXSquare extends BvComponent {}

export declare class BIconXSquareFill extends BvComponent {}

// --- END AUTO-GENERATED FILE ---
