export const ATTR_ALT = 'alt'
export const ATTR_AUTOCOMPLETE = 'autocomplete'
export const ATTR_DISABLED = 'disabled'
export const ATTR_FOR = 'for'
export const ATTR_ROLE = 'role'
export const ATTR_SRC = 'src'
export const ATTR_TABINDEX = 'tabindex'
export const ATTR_TITLE = 'title'
export const ATTR_TYPE = 'type'

// ARIA
export const ATTR_ARIA_ATOMIC = 'aria-atomic'
export const ATTR_ARIA_CHECKED = 'aria-checked'
export const ATTR_ARIA_CONTROLS = 'aria-controls'
export const ATTR_ARIA_CURRENT = 'aria-current'
export const ATTR_ARIA_DESCRIBEDBY = 'aria-describedby'
export const ATTR_ARIA_DISABLED = 'aria-disabled'
export const ATTR_ARIA_HIDDEN = 'aria-hidden'
export const ATTR_ARIA_LABEL = 'aria-label'
export const ATTR_ARIA_LIVE = 'aria-live'
export const ATTR_ARIA_PRESSED = 'aria-pressed'
