export const CALENDAR_GREGORY = 'gregory'
export const CALENDAR_LONG = 'long'
export const CALENDAR_NARROW = 'narrow'
export const CALENDAR_SHORT = 'short'
export const CALENDAR_TYPE_DATE = 'date'
export const CALENDAR_TYPE_DAY = 'day'
export const CALENDAR_TYPE_MONTH = 'month'
export const CALENDAR_TYPE_YEAR = 'year'

export const DATE_FORMAT_2_DIGIT = '2-digit'
export const DATE_FORMAT_NUMERIC = 'numeric'
