import { BvPlugin } from '../'

// Plugin that installs all plugins
export declare const componentsPlugin: BvPlugin

// Export all components as named exports
export * from './alert'
export * from './badge'
export * from './breadcrumb'
export * from './button'
export * from './button-group'
export * from './button-toolbar'
export * from './card'
export * from './carousel'
export * from './collapse'
export * from './dropdown'
export * from './embed'
export * from './form'
export * from './form-checkbox'
export * from './form-file'
export * from './form-group'
export * from './form-input'
export * from './form-radio'
export * from './form-tags'
export * from './form-select'
export * from './form-textarea'
export * from './image'
export * from './input-group'
export * from './jumbotron'
export * from './layout'
export * from './link'
export * from './list-group'
export * from './media'
export * from './modal'
export * from './nav'
export * from './navbar'
export * from './pagination'
export * from './pagination-nav'
export * from './popover'
export * from './progress'
export * from './spinner'
export * from './table'
export * from './tabs'
export * from './toast'
export * from './tooltip'
