#!/usr/bin/env bash
set -e

# Cleanup
rm -rf dist es

# Compile JS (dist/)
rollup -c scripts/rollup.config.js

# Uglify JS
# We don't use --compress for the ESM build because it removes the imports from the top
uglifyjs --compress typeofs=false --mangle --comments "/^!/" --source-map "content=dist/bootstrap-vue.js.map,includeSources,url=bootstrap-vue.min.js.map" --output dist/bootstrap-vue.min.js dist/bootstrap-vue.js
uglifyjs --compress typeofs=false --mangle --comments "/^!/" --source-map "content=dist/bootstrap-vue.common.js.map,includeSources,url=bootstrap-vue.min.common.js.map" --output dist/bootstrap-vue.min.common.js dist/bootstrap-vue.common.js
uglifyjs --mangle --comments "/^!/" --source-map "content=dist/bootstrap-vue.esm.js.map,includeSources,url=bootstrap-vue.min.esm.js.map" --output dist/bootstrap-vue.min.esm.js dist/bootstrap-vue.esm.js

# Build ES modules (es/)
npx babel src --out-dir es --ignore 'src/**/*/fixtures,src/**/*.spec.js'

# Compile SASS
node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 src/index.scss dist/bootstrap-vue.css

# Minify CSS
cleancss --level 1 --format breaksWith=lf --source-map --source-map-inline-sources --output dist/bootstrap-vue.min.css dist/bootstrap-vue.css
