#!/usr/bin/env bash
set -x -e
cd ..

# Ensure clean dist dir
[ -d dist ] && rm -rv dist
mkdir -p dist

# Gen docs
yarn docs-gen

# Prepare git
git config --global user.email "pooya@pi0.ir"
git config --global user.name "bootstrap-vue-bot"

# Fetch gh-pages
cd dist
git init
git remote add origin $GH_PAGES_REPO
git fetch origin

# Commit new docs
git add --all
git commit -m "Published by CI"
git push -ff origin master